version: 2
jobs:
  build:
    docker:
      - buildpack-deps:trusty
    services:
      - docker
    environment:
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      PRIVATE_REGISTRY: us.gcr.io/code_climate
      IMAGE_NAME: $PRIVATE_REGISTRY/$CIRCLE_PROJECT_REPONAME:b$CIRCLE_BUILD_NUM
    steps:
      - checkout
      - setup_remote_docker:
        docker_layer_caching: true
      - run:
        name: Docker info
        command: docker info && docker --version
      - run:
        name: Prebuild images
        command: make test-image

      - run:
        name: Tests
        command: make test

      - deploy:
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo $GCLOUD_JSON_KEY_BASE64 | sed 's/ //g' | base64 -d > /tmp/gcloud_key.json
            curl https://sdk.cloud.google.com | bash
            gcloud auth activate-service-account $gcloud_account_email --key-file /tmp/gcloud_key.json
            gcloud docker -a
            docker push $PRIVATE_REGISTRY/$CIRCLE_PROJECT_REPONAME:b$CIRCLE_BUILD_NUM
          fi

      - notify: # This doesn't work in 2.0
        webhooks:
          - url: https://cc-slack-proxy.herokuapp.com/circle
